/* auth */
export const FETCH_USER = "FETCH_USER";
export const LOGIN_USER = "LOGIN_USER";
export const LOGOUT_USER = "LOGOUT_USER";

/* Election searching and focusing */
export const AVAILABLE_ISSUE_FILTERS = "AVAILABLE_ISSUE_FILTERS";
export const FETCH_ELECTION = "FOCUS_ELECTION";
export const FETCH_ELECTIONS = "FETCH_ELECTIONS";
export const FILTERED_ELECTIONS = "FILTERED_ELECTIONS";
export const FOCUS_ELECTION = "FOCUS_ELECTION";
export const RECEIVE_ELECTIONS = "RECEIVE_ELECTIONS";
export const UPDATE_ELECTION_FILTER = "UPDATE_ELECTION_FILTER";

/* Candidate handling */
export const SUBMIT_CANDIDATE = "SUBMIT_CANDIDATE";

/* Voting */
export const DOWNVOTE_CANDIDATE = "DOWNVOTE_CANDIDATE";
export const UPVOTE_CANDIDATE = "UPVOTE_CANDIDATE";
export const SUBMIT_RANKING = "SUBMIT_RANKING";
